server:
  port: 7003
#Eureka配置
eureka:
  instance:
    hostname: eureka7003.com #Eureka服务端的实例名称
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己；本module就是服务器，所以不需要注册；
    fetch-registry: false #如果为false则表示自己为注册中心；
    service-url:
      #监控页面的地址写成动态
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/


