server:
  port: 8003
mybatis:
  #  别名：这里对应就是springcloud-api里面放pojo的包名
  type-aliases-package: com.chengfeng.springcloud.pojo
  #mybatis配置文件所在位置
  config-location: classpath:mybatis/mybatis-config.xml
  #  mybatis映射文件所在位置
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  application:
    #    本项目的名字,在eureka界面的application也会显示这个名称
    name: springcloud-provider-Dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db03?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

#Eureka的配置，因为8001是作为服务者，所以要表名把服务注册到哪里（即哪个注册中心，这里是7001）
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8003 #这个是页面上status的描述信息
#info配置,点实例进去的页面会展示下面的info信息
info:
  app.name: chengfeng-springcloud
  company.name: https://github.com/MajorTooooom
