server:
  port: 9527
spring:
  application:
    name: springcloud-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: zuul-9527.com
    prefer-ip-address: true
#测试阶段需要配hosts：127.0.0.1 www.chengfengLearnZuul.com
info:
  app.name: chengfeng-springcloud-zuul
  company.name: https://github.com/MajorTooooom
zuul:
  routes:
    #url中的“springcloud-provider-dept”将可以替换成/mydept/**
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: springcloud-provider-dept #不能再使用这个路径访问了；真实环境会用“*”
  prefix: /cheng #设置统一的访问前缀；